"""added mail compaign

Revision ID: 2a441bf7fd19
Revises: 32bdb69878aa
Create Date: 2025-07-10 13:34:38.265247

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a441bf7fd19'
down_revision = '32bdb69878aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_campaigns',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('template_id', sa.Integer(), sa.ForeignKey('mail_templates.id'), nullable=False),
        sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('status', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_campaigns')
    # ### end Alembic commands ###